name: Update Documentation

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Get current time
        id: current-time
        run: echo "time=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Update documentation
        run: |
          chmod +x ./run
          ./run llm:3.x
      
      - name: Upload all documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: filament-docs-3.x
          path: filament-3.x-all.md
          retention-days: 90

      - name: Retry Upload if Failed
        if: failure()
        run: |
          sleep 10
          actions/upload-artifact@v4
          with:
            name: filament-packages-3.x
            path: filament-3.x-packages-3.x.zip
            retention-days: 90
          
      - name: Upload packages documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: filament-packages-3.x
          path: filament-3.x-packages-3.x.zip
          retention-days: 90
      
      # Create a release with the latest documentation
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: filament-docs
          name: AI friendly format Filament Documentation
          body: |
            Latest Filament Documentation for LLMs
            Generated on ${{ steps.current-time.outputs.time }}
          files: |
            filament-3.x-all.md
            filament-3.x-packages-3.x.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
        
      # Update README with link to latest docs
      - name: Update README with latest docs link
        run: |
          # Get repo info
          REPO="${GITHUB_REPOSITORY}"
          
          # Create or update README with link
          if [ -f "README.md" ]; then
            # If README exists, check if section exists and update or add
            if grep -q "## Latest Documentation" README.md; then
              # Update existing section
              sed -i '/## Latest Documentation/,/^## /c\## Latest Documentation\n\nLatest documentation is available [here](https://github.com/${REPO}/releases/download/latest-docs/filament-3.x-all.md).\n\nIndividual package documentation is available as a [ZIP file](https://github.com/${REPO}/releases/download/latest-docs/filament-3.x-packages-3.x.zip).\n\n' README.md
            else
              # Add section at the end
              echo -e "\n## Latest Documentation\n\nLatest documentation is available [here](https://github.com/${REPO}/releases/download/latest-docs/filament-3.x-all.md).\n\nIndividual package documentation is available as a [ZIP file](https://github.com/${REPO}/releases/download/latest-docs/filament-3.x-packages-3.x.zip).\n" >> README.md
            fi
          else
            # Create README if it doesn't exist
            echo -e "# Filament Documentation Oven\n\n## Latest Documentation\n\nLatest documentation is available [here](https://github.com/${REPO}/releases/download/latest-docs/filament-3.x-all.md).\n\nIndividual package documentation is available as a [ZIP file](https://github.com/${REPO}/releases/download/latest-docs/filament-3.x-packages-3.x.zip).\n" > README.md
          fi
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update documentation'
          default_author: github_actions
